openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://carpark-api.test'
paths:
  /api/v1/profile:
    get:
      summary: ''
      operationId: getApiV1Profile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      security: []
    put:
      summary: ''
      operationId: putApiV1Profile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: dolorem
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: lester79@example.org
              required:
                - name
                - email
      security: []
  /api/v1/password:
    put:
      summary: ''
      operationId: putApiV1Password
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  description: ''
                  example: soluta
                password:
                  type: string
                  description: ''
                  example: libero
              required:
                - current_password
                - password
      security: []
  /api/v1/vehicles:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plate_number:
                  type: string
                  description: ''
                  example: et
              required:
                - plate_number
      security: []
  '/api/v1/vehicles/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plate_number:
                  type: string
                  description: ''
                  example: et
              required:
                - plate_number
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the vehicle.'
        example: 16
        required: true
        schema:
          type: integer
  /api/v1/parkings/start:
    post:
      summary: ''
      operationId: postApiV1ParkingsStart
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vehicle_id:
                  type: integer
                  description: ''
                  example: 9
                zone_id:
                  type: integer
                  description: ''
                  example: 11
              required:
                - vehicle_id
                - zone_id
      security: []
  '/api/v1/parkings/{parking_id}':
    get:
      summary: ''
      operationId: getApiV1ParkingsParking_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      security: []
    put:
      summary: ''
      operationId: putApiV1ParkingsParking_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      security: []
    parameters:
      -
        in: path
        name: parking_id
        description: 'The ID of the parking.'
        example: 19
        required: true
        schema:
          type: integer
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: raomrbcseuwuzkpiqjz
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: rohan.eino@example.org
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: '|U,1mF`C'
              required:
                - name
                - email
                - password
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: adaline56@example.org
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'PGa[1Z3SePM'
              required:
                - email
                - password
      security: []
  /api/v1/zones:
    get:
      summary: ''
      operationId: getApiV1Zones
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      security: []
  /api/v1/auth/logout:
    post:
      summary: ''
      operationId: postApiV1AuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Auth
    description: ''
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
